/**
 * Legal page content for Terms of Service and Privacy Policy.
 * Centralized here so tests can verify structure and content.
 */

export interface LegalSection {
  id: string;
  title: string;
  content: string;
}

// ---------- Terms of Service ----------

export const TOS_LAST_UPDATED = "2025-02-12";

export const TOS_SECTIONS: LegalSection[] = [
  {
    id: "acceptance",
    title: "1. Acceptance of Terms",
    content:
      'By accessing or using GitGood ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, you may not use the Service. You must be at least 13 years old to use GitGood, consistent with GitHub\'s minimum age requirement.',
  },
  {
    id: "description",
    title: "2. Description of Service",
    content:
      "GitGood is an AI-powered learning platform that generates personalized curricula from public GitHub repositories. The Service uses artificial intelligence to analyze code repositories and create educational content including lessons, quizzes, and coding challenges.",
  },
  {
    id: "accounts",
    title: "3. User Accounts",
    content:
      "You must authenticate via GitHub OAuth to use the Service. You are responsible for maintaining the security of your GitHub account. GitGood stores a session cookie and syncs learning progress to your GitHub repositories. You may delete your data at any time by removing the learning-tracker repository from your GitHub account.",
  },
  {
    id: "usage",
    title: "4. Acceptable Use",
    content:
      "You agree not to: (a) use the Service to analyze repositories containing malware, exploits, or harmful content; (b) attempt to bypass rate limits or abuse the AI generation features; (c) use automated tools to scrape or overload the Service; (d) share or redistribute generated curricula commercially without permission; (e) impersonate other users or misrepresent your identity.",
  },
  {
    id: "content-ownership",
    title: "5. Content Ownership & Copyright",
    content:
      "Repository content analyzed by GitGood belongs to its original authors and is subject to their respective licenses. AI-generated curricula, explanations, and quizzes are provided for personal educational use. GitGood does not claim ownership of any GitHub repository content. If you are a repository owner and wish to have your repository excluded from analysis, please contact us.",
  },
  {
    id: "dmca",
    title: "6. DMCA & Takedown Requests",
    content:
      "GitGood respects intellectual property rights. If you believe that content generated from your repository infringes your copyright, you may submit a takedown request. We will review and respond to valid requests within 72 hours. Cached curricula for the affected repository will be removed upon verification.",
  },
  {
    id: "ai-disclaimer",
    title: "7. AI-Generated Content Disclaimer",
    content:
      "Curricula, explanations, quizzes, and chat responses are generated by artificial intelligence (Google Gemini). While we strive for accuracy, AI-generated content may contain errors, omissions, or inaccuracies. The Service is intended as a learning aid and should not be relied upon as the sole source of technical information. Always refer to official documentation and the original source code.",
  },
  {
    id: "rate-limits",
    title: "8. Usage Limits & Fair Use",
    content:
      "Free tier users are subject to daily limits on AI-powered features (100 requests per day). Rate limits are enforced server-side to ensure fair access for all users. Attempts to circumvent rate limits may result in temporary or permanent suspension of access.",
  },
  {
    id: "liability",
    title: "9. Limitation of Liability",
    content:
      'The Service is provided "as is" without warranties of any kind, express or implied. GitGood shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service. This includes, but is not limited to, loss of data, loss of profits, or damages resulting from reliance on AI-generated content.',
  },
  {
    id: "termination",
    title: "10. Termination",
    content:
      "We may suspend or terminate your access to the Service at any time for violation of these terms, abusive behavior, or at our discretion. Upon termination, your learning progress remains in your own GitHub repositories. You may also terminate your account at any time by ceasing to use the Service and revoking the GitHub OAuth connection.",
  },
  {
    id: "changes",
    title: "11. Changes to Terms",
    content:
      "We may update these Terms from time to time. Continued use of the Service after changes constitutes acceptance of the updated terms. We will make reasonable efforts to notify users of significant changes.",
  },
];

// ---------- Privacy Policy ----------

export const PRIVACY_LAST_UPDATED = "2025-02-12";

export const PRIVACY_SECTIONS: LegalSection[] = [
  {
    id: "overview",
    title: "1. Overview",
    content:
      "GitGood is committed to protecting your privacy. This policy explains what data we collect, how we use it, and your rights regarding your personal information.",
  },
  {
    id: "data-collected",
    title: "2. Data We Collect",
    content:
      "We collect the following data through GitHub OAuth: your GitHub username, display name, email address, and profile picture. We also collect: learning progress data (topics completed, quiz scores, time spent), usage data (pages visited, features used, error logs), and technical data (IP address for rate limiting, browser type, device information). We do not collect passwords or GitHub access tokens on our servers — authentication is handled via Firebase Auth with httpOnly session cookies.",
  },
  {
    id: "data-use",
    title: "3. How We Use Your Data",
    content:
      "Your data is used to: (a) provide and personalize the learning experience; (b) sync learning progress to your GitHub repositories; (c) enforce rate limits and prevent abuse; (d) improve the Service through aggregated, anonymized analytics; (e) communicate important service updates. We do not sell your personal data to third parties.",
  },
  {
    id: "data-storage",
    title: "4. Data Storage & Security",
    content:
      "Learning progress is stored in your own GitHub repositories (learning-tracker), giving you full ownership and control. Session data is stored in httpOnly, secure cookies. Rate limiting data is stored in Upstash Redis with automatic expiration. We use HTTPS encryption for all data transmission, Content Security Policy headers, and server-side input sanitization to protect your data.",
  },
  {
    id: "third-parties",
    title: "5. Third-Party Services",
    content:
      "GitGood integrates with the following third-party services: GitHub (authentication, data storage, repository analysis), Google Gemini API (AI content generation — your prompts are sent to Google's servers), Firebase (authentication and session management), Upstash Redis (rate limiting), and Vercel (hosting and serverless functions). Each service has its own privacy policy governing their handling of your data.",
  },
  {
    id: "cookies",
    title: "6. Cookies & Local Storage",
    content:
      "We use: (a) a session cookie (httpOnly, secure) for authentication; (b) localStorage for user preferences, notes, bookmarks, and offline progress queue; (c) sessionStorage for temporary content caching. We do not use third-party tracking cookies. You can clear local data at any time through your browser settings.",
  },
  {
    id: "data-retention",
    title: "7. Data Retention",
    content:
      "Session cookies expire after 14 days of inactivity. Rate limiting data is automatically deleted after 24 hours. Learning progress persists in your GitHub repository until you delete it. Notes and bookmarks in localStorage persist until cleared by you or your browser. We do not retain AI conversation logs beyond the current session.",
  },
  {
    id: "user-rights",
    title: "8. Your Rights",
    content:
      "You have the right to: (a) access your data — your learning progress is in your own GitHub repository; (b) export your data — use the Export feature in your dashboard; (c) delete your data — remove the learning-tracker repository and clear browser storage; (d) revoke access — disconnect GitGood from your GitHub account in GitHub Settings > Applications. For GDPR-covered users in the EU, you may also request complete data erasure by contacting us.",
  },
  {
    id: "children",
    title: "9. Children's Privacy",
    content:
      "GitGood is not intended for children under 13 years of age, consistent with GitHub's Terms of Service. We do not knowingly collect data from children under 13. If we become aware that a user is under 13, we will promptly delete their account and associated data.",
  },
  {
    id: "changes",
    title: "10. Changes to This Policy",
    content:
      "We may update this Privacy Policy from time to time. We will notify users of material changes through the Service. The date of the most recent revision is indicated at the top of this page.",
  },
];

// ---------- Helpers ----------

export function getSectionById(
  sections: LegalSection[],
  id: string
): LegalSection | undefined {
  return sections.find((s) => s.id === id);
}

export function getTableOfContents(sections: LegalSection[]): { id: string; title: string }[] {
  return sections.map((s) => ({ id: s.id, title: s.title }));
}
